SEMANTIC_TASK_NAME = "semantic"
TOPIC_TASK_NAME = "topic"
GIBBERISH_TASK_NAME = "gibberish"
UNSAFE_PROMPT_TASK_NAME = "unsafe_prompt"
HALLUCINATION_TASK_NAME = "hallucination"
TOXICITY_TASK_NAME = "toxicity"